### ISSUE TITLE
Support Unix convention for tar modules

### ISSUE THREAD

**Issue by jfrohnhofen** [daedaleanai/dbt#74]
In Unix it is convention to include a package directory in tarballs. To support this style in DBT, we need to remove that directory when extracting the tarball.

**Comment by ptia** [comment]
How do we want deal with existing dependencies that don't do this? Do we enforce the unix convention?

**Comment by jfrohnhofen** [comment]
The only existing dependencies we currently have are the toolchains and some for HDL. Given that the number of ppl using DBT right now and the number of existing dependencies is small, I would do a breaking change and update the existing dependencies.
