### ISSUE TITLE
Build is not always correct

### ISSUE THREAD

**Issue by paulhankin** [daedaleanai/dbt#91]
Sorry, I don't have an exact repro, but I think this is a serious enough bug to report anyway.

What I did (that I think was relevant) was:
1: build a target
2: rename some files, change the BUILD.go file, and then modify one or more of the changed files.
3: build the same target

The result was that an old (deleted) method or function was still getting linked into the target, resulting in a crash when I ran the target.

Running "dbt clean" and then re-building the target solved the problem.

This caused me to waste an hour or so, as I was quite puzzled when I was debugging the code, since it was phantom code and the build process that was causing the crash.

What I expect is that builds are correct no matter what, and there's no silent correctness failures. Having uncertainty about build correctness encourages frequent "dbt clean"s, and erodes the value of incremental builds.

**Comment by jfrohnhofen** [comment]
That is unfortunate and should definitely not happen!
I tried to reproduce your problem from your description, but was also not able to.
DBT recreates the ninja file from scratch on each dbt build invocation (to avoid all those nasty caching problems). However, ninja decides what to rebuild based on file timestamps and compile command hashes.
So I have two theories:
1. Ninja screwed up: Did you reuse filenames when renaming the files? That might mess up the timestamps for ninja. I.e., the .o file produced from the old .cc file would still be newer than any of the .cc files and if compiled with the same command not trigger ninja to rebuild it.
2. DBT screwed up: The ninja rules DBT generates are not complete (i.e., they miss some dependency link) and ninja thus cannot pick up the changes. I took another look at the cc rules and did not find anything. Are you using anything besides cc.Library and cc.Binary?

I'll leave this open to gather more evidence, but don't see anything we can do without being able to reproduce the problem.

**Comment by paulhankin** [comment]
I think the problem is the behavior of "ar rv", which is used to build archives for cc.Library targets. If a file is removed from a cc.Library target, its .o file will remain in the archive. Although mostly harmless, that can cause multiple definitions of the same function, which could result in the behavior I saw.

Here's my repro:
1. Create a cc.Library target LibT with one file x.cc containing a function f()
2. dbt build LibT
3. mv x.cc y.cc
4. edit y.cc to change f a bit
5. edit BUILD.go so that LibT refers to y.cc
5. dbt build LibT

Now you have an archive libt containing x.o and y.o both containing f(), but with different definitions.

(Note that this repro can explain what I saw, since I removed a file containing a function, and re-implemented it slightly differently in a different file).

**Comment by paulhankin** [comment]
As far as I can tell, there is no option to ar to always create a new archive "ar rc" is the most likely candidate, but this only suppresses a warning if the archive doesn't already exist. So simply rm-ing the library before running ar seems to be the most obvious solution.

I'll send a fix for this issue to dbt-rules, since the problem is there and not in the dbt tool itself.

**Comment by paulhankin** [comment]
Fixed by the change to dbt-rules
